{"trial_id": "03", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "input_dim", "default": 60, "conditions": [], "values": [60, 90, 120], "ordered": true}}, {"class_name": "Choice", "config": {"name": "output_dim", "default": 1, "conditions": [], "values": [1, 3, 7], "ordered": true}}, {"class_name": "Choice", "config": {"name": "lstm_units", "default": 64, "conditions": [], "values": [64, 128], "ordered": true}}, {"class_name": "Choice", "config": {"name": "num_layers", "default": 1, "conditions": [], "values": [1, 2], "ordered": true}}, {"class_name": "Choice", "config": {"name": "loss", "default": "mse", "conditions": [], "values": ["mse", "mae", "huber"], "ordered": false}}, {"class_name": "Choice", "config": {"name": "batch_size", "default": 16, "conditions": [], "values": [16, 32, 64], "ordered": true}}], "values": {"input_dim": 60, "output_dim": 3, "lstm_units": 64, "num_layers": 2, "loss": "mse", "batch_size": 64}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\backend\\ml_lib\\tester.py\", line 55, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\vithurshan\\Downloads\\SE_PRO\\bc\\lib\\site-packages\\keras\\src\\losses\\losses.py\", line 1679, in mean_squared_error\n    return ops.mean(ops.square(y_true - y_pred), axis=-1)\nValueError: Dimensions must be equal, but are 7 and 3 for '{{node compile_loss/mse/sub}} = Sub[T=DT_FLOAT](data_1, sequential_1/dense_1/BiasAdd)' with input shapes: [?,7], [?,3].\n"}